name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        ocaml-version: [4.12.1,4.13.1,4.14.1]
    name: OCaml ${{ matrix.ocaml-version }}
    runs-on: ${{ matrix.operating-system }}
    steps:
    - uses: actions/checkout@v2
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-version }}
        opam-local-packages: |
          !ocaml-solo5-cross-aarch64.opam
    - name: Pin package
      run: opam pin add -n -t -y ocaml-solo5 .
    - name: Install ocaml-solo5 and dune
      run: opam depext -iyt ocaml-solo5 conf-libseccomp dune
    - name: Compile example with hvt
      run: MODE=hvt opam exec -- dune build --root example
    - name: Compile example with spt
      run: MODE=spt opam exec -- dune build --root example
    - name: Run example with spt
      run: opam exec -- solo5-spt example/_build/solo5/main.exe
    - name: Compile example with virtio
      run: MODE=virtio opam exec -- dune build --root example
    - name: Compile example with muen
      run: MODE=muen opam exec -- dune build --root example
    - name: Compile example with xen
      run: MODE=xen opam exec -- dune build --root example
